/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface SDOGEBondPCSHelperInterface extends ethers.utils.Interface {
  functions: {
    "deposit(address,address,address[],uint256,uint256,uint256,uint256,uint256,bytes32)": FunctionFragment;
    "owner()": FunctionFragment;
    "recoverLostToken(address)": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "router()": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "deposit",
    values: [
      string,
      string,
      string[],
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike
    ]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "recoverLostToken",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "router", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;

  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "recoverLostToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "router", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;

  events: {
    "OwnershipTransferred(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
}

export type OwnershipTransferredEvent = TypedEvent<
  [string, string] & { previousOwner: string; newOwner: string }
>;

export class SDOGEBondPCSHelper extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: SDOGEBondPCSHelperInterface;

  functions: {
    "deposit(address,address,address[],uint256,uint256,uint256,uint256,uint256,bytes32)"(
      recipient_: string,
      bond_: string,
      path_: string[],
      amount_: BigNumberish,
      amount0Min_: BigNumberish,
      amount1Min_: BigNumberish,
      deadline_: BigNumberish,
      maxPrice_: BigNumberish,
      referralCode_: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "deposit(address,address,uint256,uint256,uint256,uint256,uint256,uint256,bytes32)"(
      recipient_: string,
      bond_: string,
      amount0_: BigNumberish,
      amount1_: BigNumberish,
      amount0Min_: BigNumberish,
      amount1Min_: BigNumberish,
      deadline_: BigNumberish,
      maxPrice_: BigNumberish,
      referralCode_: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    recoverLostToken(
      token_: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    router(overrides?: CallOverrides): Promise<[string]>;

    transferOwnership(
      newOwner_: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  "deposit(address,address,address[],uint256,uint256,uint256,uint256,uint256,bytes32)"(
    recipient_: string,
    bond_: string,
    path_: string[],
    amount_: BigNumberish,
    amount0Min_: BigNumberish,
    amount1Min_: BigNumberish,
    deadline_: BigNumberish,
    maxPrice_: BigNumberish,
    referralCode_: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "deposit(address,address,uint256,uint256,uint256,uint256,uint256,uint256,bytes32)"(
    recipient_: string,
    bond_: string,
    amount0_: BigNumberish,
    amount1_: BigNumberish,
    amount0Min_: BigNumberish,
    amount1Min_: BigNumberish,
    deadline_: BigNumberish,
    maxPrice_: BigNumberish,
    referralCode_: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  owner(overrides?: CallOverrides): Promise<string>;

  recoverLostToken(
    token_: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  renounceOwnership(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  router(overrides?: CallOverrides): Promise<string>;

  transferOwnership(
    newOwner_: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    "deposit(address,address,address[],uint256,uint256,uint256,uint256,uint256,bytes32)"(
      recipient_: string,
      bond_: string,
      path_: string[],
      amount_: BigNumberish,
      amount0Min_: BigNumberish,
      amount1Min_: BigNumberish,
      deadline_: BigNumberish,
      maxPrice_: BigNumberish,
      referralCode_: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "deposit(address,address,uint256,uint256,uint256,uint256,uint256,uint256,bytes32)"(
      recipient_: string,
      bond_: string,
      amount0_: BigNumberish,
      amount1_: BigNumberish,
      amount0Min_: BigNumberish,
      amount1Min_: BigNumberish,
      deadline_: BigNumberish,
      maxPrice_: BigNumberish,
      referralCode_: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    owner(overrides?: CallOverrides): Promise<string>;

    recoverLostToken(token_: string, overrides?: CallOverrides): Promise<void>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    router(overrides?: CallOverrides): Promise<string>;

    transferOwnership(
      newOwner_: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "OwnershipTransferred(address,address)"(
      previousOwner?: string | null,
      newOwner?: string | null
    ): TypedEventFilter<
      [string, string],
      { previousOwner: string; newOwner: string }
    >;

    OwnershipTransferred(
      previousOwner?: string | null,
      newOwner?: string | null
    ): TypedEventFilter<
      [string, string],
      { previousOwner: string; newOwner: string }
    >;
  };

  estimateGas: {
    "deposit(address,address,address[],uint256,uint256,uint256,uint256,uint256,bytes32)"(
      recipient_: string,
      bond_: string,
      path_: string[],
      amount_: BigNumberish,
      amount0Min_: BigNumberish,
      amount1Min_: BigNumberish,
      deadline_: BigNumberish,
      maxPrice_: BigNumberish,
      referralCode_: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "deposit(address,address,uint256,uint256,uint256,uint256,uint256,uint256,bytes32)"(
      recipient_: string,
      bond_: string,
      amount0_: BigNumberish,
      amount1_: BigNumberish,
      amount0Min_: BigNumberish,
      amount1Min_: BigNumberish,
      deadline_: BigNumberish,
      maxPrice_: BigNumberish,
      referralCode_: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    recoverLostToken(
      token_: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    router(overrides?: CallOverrides): Promise<BigNumber>;

    transferOwnership(
      newOwner_: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    "deposit(address,address,address[],uint256,uint256,uint256,uint256,uint256,bytes32)"(
      recipient_: string,
      bond_: string,
      path_: string[],
      amount_: BigNumberish,
      amount0Min_: BigNumberish,
      amount1Min_: BigNumberish,
      deadline_: BigNumberish,
      maxPrice_: BigNumberish,
      referralCode_: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "deposit(address,address,uint256,uint256,uint256,uint256,uint256,uint256,bytes32)"(
      recipient_: string,
      bond_: string,
      amount0_: BigNumberish,
      amount1_: BigNumberish,
      amount0Min_: BigNumberish,
      amount1Min_: BigNumberish,
      deadline_: BigNumberish,
      maxPrice_: BigNumberish,
      referralCode_: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    recoverLostToken(
      token_: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    router(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner_: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
