/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  GovernorDelegateStorageV1,
  GovernorDelegateStorageV1Interface,
} from "../GovernorDelegateStorageV1";

const _abi = [
  {
    inputs: [],
    name: "admin",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "governanceToken",
    outputs: [
      {
        internalType: "contract GovernanceTokenInterface",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "implementation",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "initialProposalId",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "latestProposalIds",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "pendingAdmin",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "proposalCount",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "proposalThreshold",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "proposals",
    outputs: [
      {
        internalType: "uint256",
        name: "id",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "proposer",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "eta",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "startBlock",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "endBlock",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "forVotes",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "againstVotes",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "abstainVotes",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "thresholdAtStart",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "votesNeeded",
        type: "uint256",
      },
      {
        internalType: "bool",
        name: "canceled",
        type: "bool",
      },
      {
        internalType: "bool",
        name: "executed",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "stakedGovernanceToken",
    outputs: [
      {
        internalType: "contract StakedGovernanceTokenInterface",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "timelock",
    outputs: [
      {
        internalType: "contract TimelockInterface",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "votingDelay",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "votingPeriod",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b50610366806100206000396000f3fe608060405234801561001057600080fd5b50600436106100df5760003560e01c80635c60da1b1161008c578063da35c66411610066578063da35c6641461017d578063f851a44014610185578063f96dae0a1461018d578063fc4eee4214610195576100df565b80635c60da1b14610165578063b58131b01461016d578063d33219b414610175576100df565b806326782247116100bd57806326782247146101405780633932abb11461015557806349a757881461015d576100df565b8063013cf08b146100e457806302a251a31461011857806317977c611461012d575b600080fd5b6100f76100f23660046102c3565b61019d565b60405161010f9c9b9a999897969594939291906102f8565b60405180910390f35b61012061020b565b60405161010f91906102ef565b61012061013b366004610295565b610211565b610148610223565b60405161010f91906102db565b610120610232565b610148610238565b610148610247565b610120610256565b61014861025c565b61012061026b565b610148610271565b610148610280565b61012061028f565b600b602081905260009182526040909120805460018201546002830154600784015460088501546009860154600a87015497870154600c880154600d890154600e9099015497996001600160a01b039097169895979496939592949192909160ff808216916101009004168c565b60045481565b600c6020526000908152604090205481565b6001546001600160a01b031681565b60035481565b600a546001600160a01b031681565b6002546001600160a01b031681565b60055481565b6008546001600160a01b031681565b60075481565b6000546001600160a01b031681565b6009546001600160a01b031681565b60065481565b6000602082840312156102a6578081fd5b81356001600160a01b03811681146102bc578182fd5b9392505050565b6000602082840312156102d4578081fd5b5035919050565b6001600160a01b0391909116815260200190565b90815260200190565b9b8c526001600160a01b039a909a1660208c015260408b019890985260608a0196909652608089019490945260a088019290925260c087015260e086015261010085015261012084015215156101408301521515610160820152610180019056fea164736f6c6343000705000a";

export class GovernorDelegateStorageV1__factory extends ContractFactory {
  constructor(
    ...args: [signer: Signer] | ConstructorParameters<typeof ContractFactory>
  ) {
    if (args.length === 1) {
      super(_abi, _bytecode, args[0]);
    } else {
      super(...args);
    }
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<GovernorDelegateStorageV1> {
    return super.deploy(overrides || {}) as Promise<GovernorDelegateStorageV1>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): GovernorDelegateStorageV1 {
    return super.attach(address) as GovernorDelegateStorageV1;
  }
  connect(signer: Signer): GovernorDelegateStorageV1__factory {
    return super.connect(signer) as GovernorDelegateStorageV1__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): GovernorDelegateStorageV1Interface {
    return new utils.Interface(_abi) as GovernorDelegateStorageV1Interface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): GovernorDelegateStorageV1 {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as GovernorDelegateStorageV1;
  }
}
