/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  GovernorAlphaInterface,
  GovernorAlphaInterfaceInterface,
} from "../GovernorAlphaInterface";

const _abi = [
  {
    inputs: [],
    name: "proposalCount",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class GovernorAlphaInterface__factory {
  static readonly abi = _abi;
  static createInterface(): GovernorAlphaInterfaceInterface {
    return new utils.Interface(_abi) as GovernorAlphaInterfaceInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): GovernorAlphaInterface {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as GovernorAlphaInterface;
  }
}
