/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IPSDOGE, IPSDOGEInterface } from "../IPSDOGE";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "account_",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount_",
        type: "uint256",
      },
    ],
    name: "burnFrom",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IPSDOGE__factory {
  static readonly abi = _abi;
  static createInterface(): IPSDOGEInterface {
    return new utils.Interface(_abi) as IPSDOGEInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IPSDOGE {
    return new Contract(address, _abi, signerOrProvider) as IPSDOGE;
  }
}
