/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IReferral, IReferralInterface } from "../IReferral";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "code_",
        type: "bytes32",
      },
      {
        internalType: "uint256",
        name: "payout_",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "depositor_",
        type: "address",
      },
    ],
    name: "calcRewards",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "code_",
        type: "bytes32",
      },
      {
        internalType: "uint256",
        name: "rewards_",
        type: "uint256",
      },
    ],
    name: "depositRewards",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IReferral__factory {
  static readonly abi = _abi;
  static createInterface(): IReferralInterface {
    return new utils.Interface(_abi) as IReferralInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IReferral {
    return new Contract(address, _abi, signerOrProvider) as IReferral;
  }
}
